<?php
function vinno_module_block_info() {
	$blocks = array();
  
	$blocks['vinno_custom_block'] = array(
	  'info' => t('Vinno Custom Block'),
	);
  
	return $blocks;
  }
function vinno_module_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'vinno_custom_block':
      $block['subject'] = t('Vinno Custom Block');
      $block['content'] = _vinno_custom_block_get_content();
      break;
  }

  return $block;
}

/**
 * Helper function to generate the block content.
 */
function _vinno_custom_block_get_content() {
    global $base_url;
	global $user;
	$acc = user_load($user->uid);
		$account_name = isset($user->name) ? $user->name : '';
		$html = "<div class='header-info container'>
		<div class='header-contract'>
			<div class='header-contract--list'>
				<div class='header-contract--item'>
				<svg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='currentColor' class='bi bi-geo-alt' viewBox='0 0 16 16'>
				<path d='M12.166 8.94c-.524 1.062-1.234 2.12-1.96 3.07A31.493 31.493 0 0 1 8 14.58a31.481 31.481 0 0 1-2.206-2.57c-.726-.95-1.436-2.008-1.96-3.07C3.304 7.867 3 6.862 3 6a5 5 0 0 1 10 0c0 .862-.305 1.867-.834 2.94zM8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10z'/>
				<path d='M8 8a2 2 0 1 1 0-4 2 2 0 0 1 0 4zm0 1a3 3 0 1 0 0-6 3 3 0 0 0 0 6z'/>
			  
					<span class='header-contract--item-title'>Cửa hàng</span>
				</div>
				<div class='header-contract--item'>
				<svg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='currentColor' class='bi bi-headset' viewBox='0 0 16 16'>
				<path d='M8 1a5 5 0 0 0-5 5v1h1a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V6a6 6 0 1 1 12 0v6a2.5 2.5 0 0 1-2.5 2.5H9.366a1 1 0 0 1-.866.5h-1a1 1 0 1 1 0-2h1a1 1 0 0 1 .866.5H11.5A1.5 1.5 0 0 0 13 12h-1a1 1 0 0 1-1-1V8a1 1 0 0 1 1-1h1V6a5 5 0 0 0-5-5z'/>
			  </svg>
					<span class='header-contract--item-title'>0987654321</span>
				</div>
			</div>
		</div>
		<div class='header-logo'>
		<img src='//localhost/baitapnew/sites/all/modules/vinno_module/HPT.png' class='header-logo--image'>
		</div>
		<div class='header-usename-cart'>
			<div class='header-usename-cart--item header-cart'>
			<a href='".$base_url."/query-giohang'>
			<svg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='currentColor' class='bi bi-bag' viewBox='0 0 16 16'>
			<path d='M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5z'/>
		  </svg>
		  
				<span>Giỏ hàng</span>
				<span class='header-usename-cart--item-number-prod'>".count_giohang($user->uid)."</span>
			</div>
			</a>
			<div class='header-usename-cart--item dropdown-toggle' id='dropdownMenuUser' data-bs-toggle='dropdown' aria-expanded='false'>
			<a href='".$base_url."/user/".$user->uid."/edit'><i class='glyphicon glyphicon-user' ></i> ".$account_name." <span class='caret'></span></a>
			</div>
			<a href='".$base_url."/user/logout'>Đăng xuất</a>
			<ul class='dropdown-menu dropdown-menu-user' aria-labelledby='accountDrop'>
				<li><a href='".$base_url."/user/".$user->uid."/edit' target='_blank'>Tài khoản</a></li>
				<li><a href='".$base_url."/user/logout'>Đăng xuất</a></li>
			</ul>
		</div>
	</div>";
	return $html;
}
