<?php

/**
 * Implements hook_views_pre_render().
 */
/**
 * Implements hook_node_view().
 */
function vinno_chitiet_node_view($node, $view_mode, $langcode) {
    global $base_url;
    if($node->type == 'san_pham'){

      $nid_danhmucsp = $node->field_sanphamnew_ten['und'][0]['nid'];
      $node_danhmuc = node_load($nid_danhmucsp);
      $title_danhmuc = $node_danhmuc->title;
      $tomtat = $node_danhmuc->field_sanpham_tomtat['und'][0]['value'];
      $chitiet = $node_danhmuc->field_sanpham_chitiet['und'][0]['value'];
      $uri_img = $node_danhmuc->field_sanpham_img['und'][0]['uri'];
      if($uri_img){
          $filename = file_create_url($uri_img);
      }
      $gia_tien = isset($node->field_sanphamnew_cost['und'][0]['value']) ? $node->field_sanphamnew_cost['und'][0]['value']:'';
      $giam_gia = isset($node->field_sanphamnew_giamgia['und'][0]['value']) ? $node->field_sanphamnew_giamgia['und'][0]['value']:'';
      if (!empty($gia_tien)) {
          // Chuyển đổi chuỗi thành số để tính toán
          $gia_tien = floatval($gia_tien);
  
          // Kiểm tra nếu $giam_gia có giá trị
          if (!empty($giam_gia)) {
              // Chuyển đổi giá trị của $giam_gia từ chuỗi thành số
              $giam_gia = floatval($giam_gia);
  
              // Tính giá mới nếu có giảm giá
              $real_giatien = $gia_tien - (($gia_tien * $giam_gia) / 100);
          } else {
              // Không có giảm giá, giá mới bằng giá gốc
              $real_giatien = $gia_tien;
          }
  
          // Định dạng giá mới theo ý muốn, ví dụ:
          // $real_giatien_formatted = number_format($real_giatien, 2); // Định dạng với 2 chữ số sau dấu phẩy
      } else {
          // Không có giá gốc, xử lý tùy ý
          $real_giatien = 0; // Hoặc giá trị mặc định khác
      }
      //dsm($real_giatien);
      $html = '<section class="product container">
      <div class="product__photo">
        <div class="photo-container">
          <div class="photo-main">
            <img src='.$filename.' alt="" >
          </div>
          
        </div>
      </div>
      <div class="product__info">
        <div class="title">
          <h1>'.$title_danhmuc.'</h1>
          <span>CKC: 001 </span>
        </div>
        <div class="price">
        <span>'.$real_giatien.'đ</span>
        </div>
      
        <div class="description">
          '.$tomtat.'
        </div>
        <a href="'.$base_url.'/them-vao-gio-hang/'.$node->nid.'" class="buy--btn">Thêm vào giỏ hàng</a>
        <a href="#" class="buy--btn">Mua ngay </a>
      </div>
  </section>
  '.$chitiet.'';
  $node->content['field_sanphamnew_show'][0]['#markup'] = $html;
    }
}
